language: python
python:
  - '3.6'
install:
  - pip install pip
  - pip install setuptools
  - python setup.py install
script:
  - python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
